spring:
  application:
    name: sidutti
  ai:
    vectorstore:
      mongodb:
        initialize-schema: false
        collection-name: document
        index-name: vector_index
        path-name: embedding
      elasticsearch:
        dimensions: 768
        initialize-schema: true
    ollama:
      chat:
        model: gemma2
      embedding:
        model: mxbai-embed-large
    vertex:
      ai:
        gemini:
          projectId: basicdocumentai
          location: us-central1


  data:
    mongodb:
      uri: mongodb+srv://sidutti:1JtigZAmA4WeNOuM@sidchar.anzbaom.mongodb.net/?retryWrites=true&w=majority&appName=sidchar
      database: sample_training
      auto-index-creation: true
  elasticsearch:
    password: ElasticAdminPassword
    uris: http://192.168.1.84:30003/
    username: elastic
  codec:
    max-in-memory-size: 2GB
  threads:
    virtual:
      enabled: true
cloud:
  google:
    project-id: basicdocumentai
    location: us
    processer-id: 8fcc58a8a720a50d