spring:
  application:
    name: sidutti
  neo4j:
    uri: neo4j+s://c78a4b99.databases.neo4j.io
    authentication:
      username: neo4j
      password: ${NEO4J_PASSWORD:none}
  ai:
    vectorstore:
      mongodb:
        initialize-schema: false
        collection-name: document
        index-name: vector_index
        path-name: embedding
      elasticsearch:
        dimensions: 1024
        initialize-schema: true
        index-name: google-ai-index
      neo4j:
        database-name: neo4j
        initialize-schema: true
        embedding-dimension: 1536
    ollama:
      chat:
        model: gemma2
      embedding:
        model: mxbai-embed-large
        enabled: false
    vertex:
      ai:
        embedding:
          text:
            enabled: false
        gemini:
          projectId: basicdocumentai
          location: us-central1
          credentialsUri: file:/mnt/nas/CodeDataset/keys/serviceaccount.json
    azure:
      openai:
        embedding:
          enabled: true
          options:
            deployment-name: basic-embeddings
        api-key: ${AZURE_OPENAI_KEY}
        endpoint: https://basicai.openai.azure.com/
        chat:
          enabled: true
          options:
            deployment-name: Basic-Mini
  aop:
    proxy-target-class: false
    auto: true

  data:
    mongodb:
      uri: mongodb+srv://sidutti:1JtigZAmA4WeNOuM@sidchar.anzbaom.mongodb.net/?retryWrites=true&w=majority&appName=sidchar
      database: sample_training
      auto-index-creation: true
  elasticsearch:
    password: ElasticAdminPassword
    uris: http://192.168.1.84:30003/
    username: elastic
  codec:
    max-in-memory-size: 2GB
  threads:
    virtual:
      enabled: true
cloud:
  microsoft:
    endpoint: https://basicdocintel.cognitiveservices.azure.com/
    key: ${AZURE_KEY:none}

  google:
    cred-path: '/mnt/nas/CodeDataset/keys/serviceaccount.json'
    project-id: basicdocumentai
    location: us
    layout-processer-id: 5b561e1fd378c67a
    bucket: doaibucket

